export const LOGIN_REQ='LOGIN_REQ';
export const LOGIN_SUCC="LOGIN_SUCC";
export const LOGIN_FAILED="LOGIN_FAILED";

export const REGISTER_REQ="REGISTER_REQ";
export const REGISTER_SUCC="REGISTER_SUCC";
export const REGISTER_FAILED="REGISTER_FAILED";
export const REGISTER_RESET='REGISTER_RESET';